name: Create Archive
on:
    push:
      tags:
      - '*'     
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Generate root
      run: |
          mkdir -p ~/stressor_receptor_calc/stressor_receptor_calc && cp -R . ~/stressor_receptor_calc/stressor_receptor_calc
          ls ~/stressor_receptor_calc
    - name: Archive Release
      run: zip -qq -r stressor_receptor_calc.zip ~/stressor_receptor_calc/stressor_receptor_calc -x ".git/*" ".github/*"
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "stressor_receptor_calc.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
