name: Create Archive
on:
    push:
      tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Archive Release
    - run: cp -a . /./stressor_receptor_calc
    - run: zip -qq -r stressor_receptor_calc.zip . -x ".git/*" ".github/*"
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "stressor_receptor_calc.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
