name: Create Archive
on:
    push:
      tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
    - uses: montudor/action-zip@v1
      with:
        args: zip -qq -r stressor_receptor_calc.zip stressor_receptor_calc -x ".git/*" ".github/*"
    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "stressor_receptor_calc.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
